### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Beliavsky** [nshaffer/modern_quadpack#1]
Thanks for the package. Trying it on Windows, I needed to replace `FC = gfortran-8` with `FC = gfortran` in the makefiles. Since users are more likely to invoke gfortran with `gfortran` than `gfortran-8`, I suggest changing the makefiles.

**Comment by nshaffer** [comment]
Thanks for bringing this up. It turns out I had an uncommitted patch exactly for this. Let me know if you find any other issues with building or running the tests.
